name: learnifyunpak
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.2
  get: ^4.6.6
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.4
  responsive_grid_list: ^1.4.0
  intl: ^0.20.1
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
